repos:
- repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
  rev: v2.2.0
  hooks:
    - id: puppet-lint
      args:
        - --fail-on-warnings
        - --no-80chars-check
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.0
  hooks:
    - id: prettier
      files: ^.*.md$
